.data
mes: .asciiz "enter the number\n"                                                                                                                                                                                  
.text                                                                                                                                                                                                             
li $v0,5                                                                                                                                                                                                           
syscall                                                                                                                                                                                                            
move $a1,$v0                                                                                                                                                                                                       
jal expo                                                                                                                                                                                                           
addi $s5,$zero,2                                                                                                                                                                                                   
div $s4,$v1,$s5                                                                                                                                                                                                    
mflo $s5                                                                                                                                                                                                                                                                                                                                                                                                                     
li $v0,10                                                                                                                                                                                                          
syscall                                                                                                                                                                                                            
expo:                                                                                                                                                                                                              
addi $s0,$zero,1                                                                                                                                                                                                   
addi $s1,$zero,2                                                                                                                                                                                                   
move $s2,$a1                                                                                                                                                                                                       
while:                                                                                                                                                                                                             
bgt $s0,$s2,exit                                                                                                                                                                                                   
li $v0,1                                                                                                                                                                                                           
add $a0,$s0,$zero                                                                                                                                                                                                  
syscall                                                                                                                                                                                                            
mul $s0,$s0,$s1                                                                                                                                                                                                    
j while                                                                                                                                                                                                            
exit:                                                                                                                                                                                                              
move $v1,$s0                                                                                                                                                                                                       
jr $ra                                                                                                                                                                                                             
loop:                                                                                                                                                                                                              
lw $ra,8($sp)                                                                                                                                                                                                      
        addi $sp,$sp,4                                                                                                                                                                                             
        jr $ra  
