.data
str: .space 100                                                                                                                                                                                                    
input: .asciiz "Enter the string:"                                                                                                                                                                                 
.text                                                                                                                                                                                                              
li $v0,4                                                                                                                                                                                                           
la $a0,input                                                                                                                                                                                                       
syscall                                                                                                                                                                                                            
                                                                                                                                                                                                                   
li $v0,8                                                                                                                                                                                                           
la $a0,str                                                                                                                                                                                                         
li $a1,100                                                                                                                                                                                                         
syscall                                                                                                                                                                                                            
                                                                                                                                                                                                                   
lb $t1,str($t0)   #load first character of input string into $t1                                                                                                                                                   
l_u:                                                                                                                                                                                                               
bge $t1,97,test1  #checks if character is lower case                                                                                                                                                               
j case                                                                                                                                                                                                             
test1:                                                                                                                                                                                                             
ble $t1,122,test2  #checks if character is within lowercase range                                                                                                                                                  
j case                                                                                                                                                                                                             
test2:                                                                                                                                                                                                             
sub $t1,$t1,32  #converts lowercase to uppercase                                                                                                                                                                   
case:                                                                                                                                                                                                              
sb $t1,str($t0)  #store char in o/p                                                                                                                                                                                
add $t0,$t0,1    #move to next char in i/p                                                                                                                                                                         
bgt $t0,100,end  #end of string reached or no                                                                                                                                                                      
lb $t1,str($t0)  #load next char of i/p str to $t1                                                                                                                                                                 
beq $t1,32,space  #check if space is there                                                                                                                                                                         
u_l:                                                                                                                                                                                                               
bge $t1,65,test3  #char is uppercase or no                                                                                                                                                                         
j case                                                                                                                                                                                                             
test3:                                                                                                                                                                                                             
ble $t1,90,test4  #char within uppercase or no                                                                                                                                                                     
j case                                                                                                                                                                                                             
test4:                                                                                                                                                                                                             
add $t1,$t1,32  #convert up to low                                                                                                                                                                                 
j case                                                                                                                                                                                                             
space:                                                                                                                                                                                                             
add $t0,$t0,1  #skip space                                                                                                                                                                                         
        bgt $t0,100,end                                                                                                                                                                                            
lb $t1,str($t0)                                                                                                                                                                                                    
        beq $t1,32,space  #char is space?                                                                                                                                                                          
        j l_u                                                                                                                                                                                                      
                                                                                                                                                                                                                   
        end:                                                                                                                                                                                                       
        li $v0,4                                                                                                                                                                                                   
        la $a0,str                                                                                                                                                                                                 
        syscall                                                                                                                                                                                                    
        li $v0,10                                                                                                                                                                                                  
        syscall        