.data                                                                                                                                                                                                              
size: .asciiz "Enter the no. of terms:"                                                                                                                                                                            
ans1: .asciiz "F_"                                                                                                                                                                                                 
ans2: .asciiz " = "                                                                                                                                                                                                
endl: .asciiz "\n"                                                                                                                                                                                                 
.text                                                                                                                                                                                                              
main:                                                                                                                                                                                                              
li $v0,4                                                                                                                                                                                                           
la $a0,size                                                                                                                                                                                                        
syscall                                                                                                                                                                                                            
li $v0,5                                                                                                                                                                                                           
syscall                                                                                                                                                                                                            
move $s0,$v0                                                                                                                                                                                                       
li $t0,-1                                                                                                                                                                                                  
loop:                                                                                                                                                                                                              
        add $t0,$t0,1                                                                                                                                                                                      
        beq $t0,$s0,exit                                                                                                                                                                                     
        move $a0,$t0                                                                                                                                                                            
        jal fib                                                                                                                                                                                                    
        move $a1,$v0                                                                                                                                               
        jal printf                                                                                                                                                                                                 
        j loop                                                                                                                                                                                                     
        exit:                                                                                                                                                                                                      
        li $v0,10                                                                                                                                                              
        syscall                                                                                                                                                                                                    
 printf:                                                                                                                                                                                                    
        li $v0,4                                                                                                                                                                                                   
        la $a0,ans1                                                                                                                                                                                          
        syscall                                                                                                                                                                                                    
        move $a0,$t0                                                                                                                                                                                          
        li $v0,1                                                                                                                                                                                                   
        syscall                                                                                                                                                                                                    
        li $v0,4                                                                                                                                                                                                   
        la $a0,ans2                                                                                                                                                                                            
        syscall                                                                                                                                                                                                    
        move $a0,$a1                                                                                                                                                                                               
        li $v0,1        # print fib(i)                                                                                                                                                                                     
        syscall                                                                                                                                                                                                    
        li $v0,4                                                                                                                                                                                                   
        la $a0,endl     # \n                                                                                                                                                                                       
        syscall                                                                                                                                                                                                    
        jr $ra                                                                                                                                                                                                     
fib:                                                                                                                                                                                                       
beqz $a0,zero   # if(n == 0)                                                                                                                                                                               
beq $a0,1,one                                                                                                                                                                                                                                                                                                                                                              
 sub $sp,$sp,4                                                                                                                                                                                              
sw $ra,0($sp)                                                                                                                                                                                                      
sub $a0,$a0,1                                                                                                                                                                   
jal fib         # fib(n-1)                                                                                                                                                                                         
add $a0,$a0,1                                                                                                                                                     
lw $ra,0($sp)                                                                                                                                                                                                      
add $sp,$sp,4                                                                                                                                                                                                                                                                                                                                                                         
sub $sp,$sp,4                                                                                                                                                                                              
sw $v0,0($sp)                                                                                                                                                                                                                                                                                                                                             
sub $sp,$sp,4                                                                                                                                                                                              
sw $ra,0($sp)                                                                                                                                                                                                      
sub $a0,$a0,2                                                                                                                                                               
jal fib         # fib(n-2)                                                                                                                                                                                         
add $a0,$a0,2                                                                                                                                                       
lw $ra,0($sp)                                                                                                                                                                                                      
add $sp,$sp,4                                                                                                                                                                                              
                                                                                                                                                                                
lw $s1,0($sp)                                                                                                                                                                      
 add $sp,$sp,4                                                                                                                                                                                                                                                                                                                                                                             
add $v0,$v0,$s1         # return fib(n-1) + fib(n-2)                                                                                                                                                               
jr $ra                                                                                                                                                                                                     
zero:                                                                                                                                                                                                      
      li $v0,0                                                                                                                                                                                   
      jr $ra                                                                                                                                                                                                     
one:                                                                                                                                                                                                       
      li $v0,1                                                                                                                                                                                        
      jr $ra     