.data                                                                                                                                                                                                              
mat1 : .word 1, 2, 3, 4,                                                                                                                                                                                           
     5, 6, 7, 8,                                                                                                                                                                                                   
     9, 10, 11, 12,                                                                                                                                                                                                
     13, 14, 15, 16                                                                                                                                                                                                
                                                                                                                                                                                                                   
     mat2 : .word 1, 2, 3, 4,                                                                                                                                                                                      
     5, 6, 7, 8,                                                                                                                                                                                                   
     9, 10, 11, 12,                                                                                                                                                                                                
     13, 14, 15, 16                                                                                                                                                                                                
                                                                                                                                                                                                                   
     sp : .asciiz " "                                                                                                                                                                                              
                                                                                                                                                                                                                   
     n  : .asciiz "\n"                                                                                                                                                                                             
                                                                                                                                                                                                                   
     r1 : .word 4                                                                                                                                                                                                  
     c1 : .word 4                                                                                                                                                                                                  
     r2 : .word 4                                                                                                                                                                                                  
     c2 : .word 4                                                                                                                                                                                                  
                                                                                                                                                                                                                   
 .text                                                                                                                                                                                                                                                                                                                                                                                                                     
     la $s0, mat1                                                                                                                                                                                                  
     la $s1, mat2                                                                                                                                                                                                  
                                                                                                                                                                                                                   
     li $t0, 0  #sum                                                                                                                                                                                                
     lw $t1, r1                                                                                                                                                                                                    
     lw $t2, c1                                                                                                                                                                                                    
     li $t3, -1 #ol                                                                                                                                                                                                
                                                                                                                                                                                                                   
     li $t7, 4     
                                                                                                                                                                                                     
     loop1:                                                                                                                                                                                                        
     addi $t3, $t3, 1                                                                                                                                                                                              
     li $v0, 4                                                                                                                                                                                                     
     la $a0, n                                                                                                                                                                                                     
     syscall                                                                                                                                                                                                       
     bge $t3, $t1, exit                                                                                                                                                                                            
     li $t4, 0 #il                                                                                                                                                                                                 
                                                                                                                                                                                                                   
     loop2:                                                                                                                                                                                                        
     bge $t4, $t2, loop1                                                                                                                                                                                                                                                                                                                                                                                                         
     mul $t5, $t3, $t2                                                                                                                                                                                             
     add $t5, $t5, $t4                                                                                                                                                                                             
     mul $t6, $t5, 4                                                                                                                                                                                               
     lw $s2, mat1($t6)                                                                                                                                                                                          
     lw $s3, mat2($t6)                                                                                                                                                                                                  
     add $t0, $s2, $s3                                                                                                                                                                                                                                                                                                                                                                                                           
     addi $t4, $t4, 1                                                                                                                                                                                                                                                                                                                                                                                                     
     li $v0, 1                                                                                                                                                                                                  
     move $a0, $t0                                                                                                                                                                                              
     syscall                                                                                                                                                                                                    
     li $v0, 4                                                                                                                                                                                                  
     la $a0, sp                                                                                                                                                                                                 
     syscall                                                                                                                                                                                                    
                                                                                                                                                                                                                   
     j loop2                                                                                                                                                                                                    
                                                                                                                                                                                                                
   exit:                                                                                                                                                                                                      
      li $v0, 10                                                                                                                                                                                                 
      syscall                                                                                                                                                                                                                        
         