.data                                                                                                                                                                                                            
mat1 : .word 1, 2, 3, 4,                                                                                                                                                                                           
     1, 2, 3, 4,                                                                                                                                                                                                   
     1, 2, 3, 4,                                                                                                                                                                                                   
     1, 2, 3, 4                                                                                                                                                                                                    
                                                                                                                                                                                                                   
     mat2 : .word 1, 2, 3, 4,                                                                                                                                                                                      
     1, 2, 3, 4,                                                                                                                                                                                                   
     1, 2, 3, 4,                                                                                                                                                                                                   
     1, 2, 3, 4                                                                                                                                                                                                    
                                                                                                                                                                                                                   
     space : .asciiz " "                                                                                                                                                                                           
                                                                                                                                                                                                                   
     new_line : .asciiz "\n"                                                                                                                                                                                       
                                                                                                                                                                                                                   
     r1 : .word 4                                                                                                                                                                                                  
     c1 : .word 4                                                                                                                                                                                                  
     r2 : .word 4                                                                                                                                                                                                  
     c2 : .word 4                                                                                                                                                                                                  
                                                                                                                                                                                                                   
  .text                                                                                                                                                                                                         
                                                                                                                                                                                                                   
     li $t0, -1 #l1                                                                                                                                                                                                
     lw $t1, r1 #r1                                                                                                                                                                                                
     loop1 :                                                                                                                                                                                                       
     addi $t0, $t0, 1                                                                                                                                                                                              
     bge $t0, $t1, exit                                                                                                                                                                                            
                                                                                                                                                                                                                   
     li $t2, -1 #l2                                                                                                                                                                                                
     lw $t3, c2 #c2                                                                                                                                                                                                
                                                                                                                                                                                                                   
     li $v0, 4                                                                                                                                                                                                     
     la $a0, new_line                                                                                                                                                                                              
     syscall                                                                                                                                                                                                       
     loop2:                                                                                                                                                                                                        
     addi $t2, $t2, 1                                                                                                                                                                                              
     bge $t2, $t3, loop1                                                                                                                                                                                           
                                                                                                                                                                                                                   
     li $t4, 0 #l3                                                                                                                                                                                                 
     lw $t5, c1 #c1                                                                                                                                                                                                
     li $s5, 0 #sum                                                                                                                                                                                                
                                                                                                                                                                                                                   
     loop3:                                                                                                                                                                                                        
     bge $t4, $t5, next                                                                                                                                                                                            
                                                                                                                                                                                                                   
     li $t6, 0                                                                                                                                                                                                     
     li $t7, 0                                                                                                                                                                                                     
     li $s1, 4                                                                                                                                                                                                     
                                                                                                                                                                                                                   
     mul $s0, $t0, $t5 #ik                                                                                                                                                                                         
     add $s0, $s0, $t4                                                                                                                                                                                             
        mul $s0, $s0, $s1                                                                                                                                                                                          
lw $s2, mat1($s0)                                                                                                                                                                                                  
                                                                                                                                                                                                                   
        mul $s0, $t4, $t3 #kj                                                                                                                                                                                      
        add $s0, $s0, $t2                                                                                                                                                                                          
        mul $s0, $s0, $s1                                                                                                                                                                                          
lw $s3, mat2($s0)                                                                                                                                                                                                  
                                                                                                                                                                                                                   
        mul $s4, $s2, $s3                                                                                                                                                                                          
        add $s5, $s5, $s4                                                                                                                                                                                          
                                                                                                                                                                                                                   
        addi $t4, $t4, 1                                                                                                                                                                                           
        j loop3                                                                                                                                                                                                    
                                                                                                                                                                                                                   
        next:                                                                                                                                                                                                      
        li $v0, 1                                                                                                                                                                                                  
        move $a0, $s5                                                                                                                                                                                              
        syscall                                                                                                                                                                                                    
                                                                                                                                                                                                                   
        li $v0, 4                                                                                                                                                                                                  
        la $a0, space                                                                                                                                                                                              
        syscall                                                                                                                                                                                                    
                                                                                                                                                                                                                   
        j loop2                                                                                                                                                                                                    
                                                                                                                                                                                                                   
        exit:                                                                                                                                                                                                      
        li $v0, 10                                                                                                                                                                                                 
        syscall      